String sendFinalResults(int num_correct, int num_questions) {
  int num_wrong = num_questions - num_correct;

  int perc_corr = (int)(num_correct * 100) / num_questions;
  int perc_wrong = (int)(num_wrong * 100) / num_questions;

  String ptr = "";
  ptr += "<!DOCTYPE html>";
  ptr += "<html>";
  ptr += "    <head>";
  ptr += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\", user-scalable=no>";
  ptr += "        <title>Results page</title>";
  ptr += "        <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
  ptr += "    </head>";
  ptr += "    <body>";
  ptr += "        <img class=\"background\" src=\"/background.jpg\"/>";
  ptr += "        <main>";
  ptr += "            <div class=\"cover-disconnect\">";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-header\">";
  ptr += "                <h2>Your score</h2>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-main\">";
  ptr += "                <div class=\"cover__text-blur\">";
  ptr += "                    <div class=\"score\">";
  ptr += "                        <h5>Wrong</h5>";
  ptr += "                        <div class=\"bar\">";
  if (perc_wrong != 0)
    ptr += "                            <div class=\"wrong wrong-" + String(perc_wrong) + "\"><h3>" + String(num_wrong) + "</h4></div>";
  if (perc_corr != 0)
    ptr += "                            <div class=\"correct corr-" + String(perc_corr) + "\"><h3>" + String(num_correct) + "</h4></div>";
  ptr += "                        </div>";
  ptr += "                        <h5>Correct</h5>";
  ptr += "                    </div>";
  ptr += "                </div>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-footer\">";
  ptr += "                <a href=\"/disconnect\" class=\"button\">Exit</a>";
  ptr += "            </div>";
  ptr += "        </main>";
  ptr += "    </body>";
  ptr += "    <script type=\"text/javascript\">";
  ptr += "        if(window.innerHeight <= 600) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"10px\";";
  ptr += "            }";
  ptr += "            let h4s = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<h4s.length; i++) {";
  ptr += "                h4s[i].style.fontSize = \"15px\";";
  ptr += "            }";
  ptr += "            let h5s = document.getElementsByTagName(\"h5\");";
  ptr += "            for(i=0; i<h5s.length; i++) {";
  ptr += "                h5s[i].style.fontSize = \"13px\";";
  ptr += "            }";
  ptr += "            let h3s = document.getElementsByTagName(\"h3\");";
  ptr += "            for(i=0; i<h3s.length; i++) {";
  ptr += "                h3s[i].style.fontSize = \"13px\";";
  ptr += "            }";
  ptr += "            let scores = document.getElementsByClassName(\"score\");";
  ptr += "            for(i=0; i<scores.length; i++) {";
  ptr += "                scores[i].style.height = \"80%\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "        if(window.innerHeight >= 1000) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"30px\";";
  ptr += "            }";
  ptr += "            let h4s = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<h4s.length; i++) {";
  ptr += "                h4s[i].style.fontSize = \"45px\";";
  ptr += "            }";
  ptr += "            let h3s = document.getElementsByTagName(\"h3\");";
  ptr += "            for(i=0; i<h3s.length; i++) {";
  ptr += "                h3s[i].style.fontSize = \"40px\";";
  ptr += "            }";
  ptr += "            let h5s = document.getElementsByTagName(\"h5\");";
  ptr += "            for(i=0; i<h5s.length; i++) {";
  ptr += "                h5s[i].style.fontSize = \"40px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "    </script>";
  ptr += "</html>";

  return ptr;

}

String sendPResults(int quest_num, String result) {
  String ptr = "";
  ptr += "<!DOCTYPE html>";
  ptr += "<html>";
  ptr += "    <head>";
  ptr += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\", user-scalable=no>";
  ptr += "        <title>Welcome page</title>";
  ptr += "        <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
  ptr += "    </head>";
  ptr += "    <body>";
  ptr += "        <img class=\"background\" src=\"/background.jpg\"/>";
  ptr += "        <main>";
  ptr += "            <div class=\"cover-disconnect\">";
  ptr += "                <a href=\"/disconnect\" class=\"disconnect\"> Disconnect </a>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-header\">";
  ptr += "                <h2>" + String(quest_num) + ". Question</h3>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-main\">";
  ptr += "                <div class=\"cover__text-blur\">";
  ptr += "                    <div class=\"cover__text\">";
  ptr += "                        <h4>" + result + "</h4>";
  ptr += "                    </div>";
  ptr += "                </div>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-footer\">";
  ptr += "                <a href=\"/question\" class=\"button btn-next\"> Next </a>";
  ptr += "            </div>";
  ptr += "        </main>";
  ptr += "    </body>";
  ptr += "    <script type=\"text/javascript\">";
  ptr += "        if(window.innerHeight <= 600) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"10px\";";
  ptr += "            }";
  ptr += "            let hs = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<hs.length; i++) {";
  ptr += "                hs[i].style.fontSize = \"15px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "        if(window.innerHeight >= 1000) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"30px\";";
  ptr += "            }";
  ptr += "            let hs = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<hs.length; i++) {";
  ptr += "                hs[i].style.fontSize = \"45px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "        document.getElementsByClassName(\"btn-next\")[0].style.visibility = \"hidden\";";
  ptr += "        setTimeout(function() {";
  ptr += "          document.getElementsByClassName(\"btn-next\")[0].style.visibility = \"visible\";";
  ptr += "        }, 2000);";
  ptr += "    </script>";
  ptr += "</html>";

  return ptr;

}

String sendQuestionPage(int quest_num, String question) {
  String ptr = "";
  ptr += "<!DOCTYPE html>";
  ptr += "<html>";
  ptr += "    <head>";
  ptr += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\", user-scalable=no>";
  ptr += "        <title>Question " + String(quest_num) + "</title>";
  ptr += "        <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
  ptr += "    </head>";
  ptr += "    <body>";
  ptr += "        <img class=\"background\" src=\"/background.jpg\"/>";
  ptr += "        <main>";
  ptr += "            <div class=\"cover-disconnect\">";
  ptr += "                <a href=\"/disconnect\" class=\"disconnect\"> Disconnect </a>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-header\">";
  ptr += "                <h2>" + String(quest_num) + ". Question</h3>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-main\">";
  ptr += "                <div class=\"cover__text-blur\">";
  ptr += "                    <div class=\"cover__text\">";
  ptr += "                        <h4>" + question + "</h4>";
  ptr += "                    </div>";
  ptr += "                </div>";
  ptr += "            </div>";
  ptr += "            <div class=\"cover cover-footer\">";
  ptr += "                <a href=\"/false\" class=\"button\"> False </a>";
  ptr += "                <a href=\"/true\" class=\"button\"> True </a>";
  ptr += "            </div>";
  ptr += "        </main>";
  ptr += "    </body>";
  ptr += "    <script type=\"text/javascript\">";
  ptr += "        if(window.innerHeight <= 600) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"10px\";";
  ptr += "            }";
  ptr += "            let hs = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<hs.length; i++) {";
  ptr += "                hs[i].style.fontSize = \"15px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "        if(window.innerHeight >= 1000) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"30px\";";
  ptr += "            }";
  ptr += "            let hs = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<hs.length; i++) {";
  ptr += "                hs[i].style.fontSize = \"45px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "    </script>";
  ptr += "</html>";

  return ptr;
}

String sendHomePage() {
  String ptr = "";
  ptr += "<!DOCTYPE html>";
  ptr += "<html>";
  ptr += "  <head>";
  ptr += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
  ptr += "    <title>Welcome page</title>";
  ptr += "    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">";
  ptr += "  </head>";
  ptr += "  <body>";
  ptr += "    <img class=\"background\" src=\"/background.jpg\"/>";
  ptr += "    <main>";
  ptr += "      <div class=\"cover-disconnect\">";
  ptr += "            </div>";
  ptr += "      <div class=\"cover cover-header\">";
  ptr += "        <img class=\"upper_logo\" src=\"/logo_footer.png\"/>";
  ptr += "      </div>";
  ptr += "      <div class=\"cover cover-main\">";
  ptr += "        <div class=\"cover__text-blur\">";
  ptr += "          <div class=\"cover__text\">";
  ptr += "            <h4>Welcome!</h4>";
  ptr += "            <h4>The robot is studying also humans and is testing their knowledge about space.</h4>";
  ptr += "            <p>Give your answers as good as possible to increase the score!</p>";
  ptr += "          </div>";
  ptr += "        </div>";
  ptr += "      </div>";
  ptr += "      <div class=\"cover cover-footer\">";
  ptr += "        <a href=\"/start\" class=\"button\"> Start </a> ";
  ptr += "      </div>";
  ptr += "    </main>";
  ptr += "  </body>";
  ptr += "  <script type=\"text/javascript\">";
  ptr += "    if(window.innerHeight <= 600) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"10px\";";
  ptr += "            }";
  ptr += "            let hs = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<hs.length; i++) {";
  ptr += "                hs[i].style.fontSize = \"15px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "        if(window.innerHeight >= 1000) {";
  ptr += "            let ps = document.getElementsByTagName(\"p\");";
  ptr += "            for(i=0; i<ps.length; i++) {";
  ptr += "                ps[i].style.fontSize = \"30px\";";
  ptr += "            }";
  ptr += "            let hs = document.getElementsByTagName(\"h4\");";
  ptr += "            for(i=0; i<hs.length; i++) {";
  ptr += "                hs[i].style.fontSize = \"45px\";";
  ptr += "            }";
  ptr += "        }";
  ptr += "  </script>";
  ptr += "</html>";

  return ptr;
}

String sendCss() {
  String ptr = "";
  ptr += "/* ! Base Style */";
  ptr += "";
  ptr += "body {";
  ptr += "  font-family: Helvetica;";
  ptr += "  position: relative;";
  ptr += "  z-index: 1;";
  ptr += "  margin: 0;";
  ptr += "  background-color: #00000000;";
  ptr += "  opacity: 0.9;";
  ptr += "}";
  ptr += "";
  ptr += ".background {";
  ptr += "  position: absolute;";
  ptr += "  width: 100%;";
  ptr += "  height: 100%;";
  ptr += "  overflow: hidden;";
  ptr += "  margin: 0px;";
  ptr += "  z-index: -10;";
  ptr += "  filter: blur(8px) brightness(1.3);";
  ptr += "  opacity: 1";
  ptr += "}";
  ptr += "";
  ptr += "main {";
  ptr += "  height: 100vh;";
  ptr += "}";
  ptr += "";
  ptr += "h2 { color: #eee; font-size: 30px; }";
  ptr += "h4 { color: #202020; font-size: 22px; font-weight: bold; margin: 5px; margin-top: 0px; }";
  ptr += "p { color: #202020; font-size: 14px; }";
  ptr += "";
  ptr += "/* ! Cover */";
  ptr += ".cover {";
  ptr += "    display: flex;";
  ptr += "    justify-content: center;";
  ptr += "}";
  ptr += "";
  ptr += ".cover-disconnect { height: 10%; display: flex; align-items: center; }";
  ptr += ".cover-header { height: 20%; align-items: flex-end;}";
  ptr += ".cover-main { height: 55%; align-items: center;}";
  ptr += ".cover-footer { height: 15%; align-items: baseline;}";
  ptr += "";
  ptr += ".cover__text-blur {";
  ptr += "  width: 100%;";
  ptr += "  height: 55%;";
  ptr += "  text-align: center;";
  ptr += "  background: rgba(255,255,255, 0.6) 0% 0% no-repeat padding-box;";
  ptr += "  border-radius: 20px;";
  ptr += "  margin: 25px 40px;";
  ptr += "  opacity: 0.88;";
  ptr += "  backdrop-filter: blur(20px);";
  ptr += "}";
  ptr += "";
  ptr += ".cover__text {";
  ptr += "  padding: 20px 0px;";
  ptr += "  display: flex;";
  ptr += "  justify-content: center;";
  ptr += "  align-items: center;";
  ptr += "  flex-direction: column;";
  ptr += "  height: 90%;";
  ptr += "  width: 100%;";
  ptr += "}";
  ptr += "";
  ptr += "/* Upper logo */";
  ptr += "";
  ptr += ".upper_logo {";
  ptr += "  width: 30%;";
  ptr += "  height: 70%;";
  ptr += "  margin-bottom: 0px;";
  ptr += "}";
  ptr += "";
  ptr += "/* Button style */";
  ptr += "";
  ptr += ".button {";
  ptr += "  width: 30%;";
  ptr += "  backdrop-filter: blur(20px) ;";
  ptr += "  background-color: rgba(25, 25, 25, 0.1);";
  ptr += "  text-align: center;";
  ptr += "  border: none;";
  ptr += "  color: black;";
  ptr += "  padding: 15px 20px;";
  ptr += "  text-decoration: none;";
  ptr += "  font-size: 25px;";
  ptr += "  cursor: pointer;";
  ptr += "  border-radius: 20px;";
  ptr += "  margin: 20px;";
  ptr += "  margin-top: 0px;";
  ptr += "}";
  ptr += "";
  ptr += ".disconnect {";
  ptr += "  text-align: center;";
  ptr += "  backdrop-filter: blur(50px);";
  ptr += "  background-color: rgba(30, 30, 30, 0.6);";
  ptr += "  border-radius: 10px;";
  ptr += "  margin-left: 10px;";
  ptr += "  padding: 5px 15px;";
  ptr += "  font-size: 20px;";
  ptr += "  color: #eeeeee;";
  ptr += "  text-decoration: none;";
  ptr += "}";
  ptr += "";
  ptr += ".button-on { background-color: #3498db; }";
  ptr += ".button-on:active { background-color: #2980b9; }";
  ptr += ".button-off { background-color: #34495e; }";
  ptr += ".button-off:active { background-color: #2c3e50; }";
  ptr += "";
  ptr += "/* Final page answers */";
  ptr += "";
  ptr += ".score {";
  ptr += "  height: 85%;";
  ptr += "  padding: 10px;";
  ptr += "}";
  ptr += "";
  ptr += ".bar {";
  ptr += "  height: 70%;";
  ptr += "  width: 20%;";
  ptr += "  color: #FFFFFF;";
  ptr += "  margin-left: 40%;";
  ptr += "}";
  ptr += "";
  ptr += ".wrong {";
  ptr += "  background-color: #A7A6A4; ";
  ptr += "  display: flex;";
  ptr += "  align-items: center;";
  ptr += "  justify-content: center;";
  ptr += "  border-radius: 20px 20px 0px 0px;";
  ptr += "}";
  ptr += "";
  ptr += ".correct {";
  ptr += "  background-color: #201F1D;";
  ptr += "  display: flex;";
  ptr += "  align-items: center;";
  ptr += "  justify-content: center;";
  ptr += "  border-radius: 0px 0px 20px 20px;";
  ptr += "}";
  ptr += "";
  ptr += "h5 { color: #202020; font-size: 18px; font-weight: bold; margin: 10px; }";
  ptr += "";
  ptr += ".wrong-0 { height: 0%; }";
  ptr += ".wrong-1 { height: 1%; }";
  ptr += ".wrong-2 { height: 2%; }";
  ptr += ".wrong-3 { height: 3%; }";
  ptr += ".wrong-4 { height: 4%; }";
  ptr += ".wrong-5 { height: 5%; }";
  ptr += ".wrong-6 { height: 6%; }";
  ptr += ".wrong-7 { height: 7%; }";
  ptr += ".wrong-8 { height: 8%; }";
  ptr += ".wrong-9 { height: 9%; }";
  ptr += ".wrong-10 { height: 10%; }";
  ptr += ".wrong-11 { height: 11%; }";
  ptr += ".wrong-12 { height: 12%; }";
  ptr += ".wrong-13 { height: 13%; }";
  ptr += ".wrong-14 { height: 14%; }";
  ptr += ".wrong-15 { height: 15%; }";
  ptr += ".wrong-16 { height: 16%; }";
  ptr += ".wrong-17 { height: 17%; }";
  ptr += ".wrong-18 { height: 18%; }";
  ptr += ".wrong-19 { height: 19%; }";
  ptr += ".wrong-20 { height: 20%; }";
  ptr += ".wrong-21 { height: 21%; }";
  ptr += ".wrong-22 { height: 22%; }";
  ptr += ".wrong-23 { height: 23%; }";
  ptr += ".wrong-24 { height: 24%; }";
  ptr += ".wrong-25 { height: 25%; }";
  ptr += ".wrong-26 { height: 26%; }";
  ptr += ".wrong-27 { height: 27%; }";
  ptr += ".wrong-28 { height: 28%; }";
  ptr += ".wrong-29 { height: 29%; }";
  ptr += ".wrong-30 { height: 30%; }";
  ptr += ".wrong-31 { height: 31%; }";
  ptr += ".wrong-32 { height: 32%; }";
  ptr += ".wrong-33 { height: 33%; }";
  ptr += ".wrong-34 { height: 34%; }";
  ptr += ".wrong-35 { height: 35%; }";
  ptr += ".wrong-36 { height: 36%; }";
  ptr += ".wrong-37 { height: 37%; }";
  ptr += ".wrong-38 { height: 38%; }";
  ptr += ".wrong-39 { height: 39%; }";
  ptr += ".wrong-40 { height: 40%; }";
  ptr += ".wrong-41 { height: 41%; }";
  ptr += ".wrong-42 { height: 42%; }";
  ptr += ".wrong-43 { height: 43%; }";
  ptr += ".wrong-44 { height: 44%; }";
  ptr += ".wrong-45 { height: 45%; }";
  ptr += ".wrong-46 { height: 46%; }";
  ptr += ".wrong-47 { height: 47%; }";
  ptr += ".wrong-48 { height: 48%; }";
  ptr += ".wrong-49 { height: 49%; }";
  ptr += ".wrong-50 { height: 50%; }";
  ptr += ".wrong-51 { height: 51%; }";
  ptr += ".wrong-52 { height: 52%; }";
  ptr += ".wrong-53 { height: 53%; }";
  ptr += ".wrong-54 { height: 54%; }";
  ptr += ".wrong-55 { height: 55%; }";
  ptr += ".wrong-56 { height: 56%; }";
  ptr += ".wrong-57 { height: 57%; }";
  ptr += ".wrong-58 { height: 58%; }";
  ptr += ".wrong-59 { height: 59%; }";
  ptr += ".wrong-60 { height: 60%; }";
  ptr += ".wrong-61 { height: 61%; }";
  ptr += ".wrong-62 { height: 62%; }";
  ptr += ".wrong-63 { height: 63%; }";
  ptr += ".wrong-64 { height: 64%; }";
  ptr += ".wrong-65 { height: 65%; }";
  ptr += ".wrong-66 { height: 66%; }";
  ptr += ".wrong-67 { height: 67%; }";
  ptr += ".wrong-68 { height: 68%; }";
  ptr += ".wrong-69 { height: 69%; }";
  ptr += ".wrong-70 { height: 70%; }";
  ptr += ".wrong-71 { height: 71%; }";
  ptr += ".wrong-72 { height: 72%; }";
  ptr += ".wrong-73 { height: 73%; }";
  ptr += ".wrong-74 { height: 74%; }";
  ptr += ".wrong-75 { height: 75%; }";
  ptr += ".wrong-76 { height: 76%; }";
  ptr += ".wrong-77 { height: 77%; }";
  ptr += ".wrong-78 { height: 78%; }";
  ptr += ".wrong-79 { height: 79%; }";
  ptr += ".wrong-80 { height: 80%; }";
  ptr += ".wrong-81 { height: 81%; }";
  ptr += ".wrong-82 { height: 82%; }";
  ptr += ".wrong-83 { height: 83%; }";
  ptr += ".wrong-84 { height: 84%; }";
  ptr += ".wrong-85 { height: 85%; }";
  ptr += ".wrong-86 { height: 86%; }";
  ptr += ".wrong-87 { height: 87%; }";
  ptr += ".wrong-88 { height: 88%; }";
  ptr += ".wrong-89 { height: 89%; }";
  ptr += ".wrong-90 { height: 90%; }";
  ptr += ".wrong-91 { height: 91%; }";
  ptr += ".wrong-92 { height: 92%; }";
  ptr += ".wrong-93 { height: 93%; }";
  ptr += ".wrong-94 { height: 94%; }";
  ptr += ".wrong-95 { height: 95%; }";
  ptr += ".wrong-96 { height: 96%; }";
  ptr += ".wrong-97 { height: 97%; }";
  ptr += ".wrong-98 { height: 98%; }";
  ptr += ".wrong-99 { height: 99%; }";
  ptr += ".wrong-100 { height: 100%; border-radius: 20px; }";
  ptr += "";
  ptr += ".corr-1 { height: 1%; }";
  ptr += ".corr-2 { height: 2%; }";
  ptr += ".corr-3 { height: 3%; }";
  ptr += ".corr-4 { height: 4%; }";
  ptr += ".corr-5 { height: 5%; }";
  ptr += ".corr-6 { height: 6%; }";
  ptr += ".corr-7 { height: 7%; }";
  ptr += ".corr-8 { height: 8%; }";
  ptr += ".corr-9 { height: 9%; }";
  ptr += ".corr-10 { height: 10%; }";
  ptr += ".corr-11 { height: 11%; }";
  ptr += ".corr-12 { height: 12%; }";
  ptr += ".corr-13 { height: 13%; }";
  ptr += ".corr-14 { height: 14%; }";
  ptr += ".corr-15 { height: 15%; }";
  ptr += ".corr-16 { height: 16%; }";
  ptr += ".corr-17 { height: 17%; }";
  ptr += ".corr-18 { height: 18%; }";
  ptr += ".corr-19 { height: 19%; }";
  ptr += ".corr-20 { height: 20%; }";
  ptr += ".corr-21 { height: 21%; }";
  ptr += ".corr-22 { height: 22%; }";
  ptr += ".corr-23 { height: 23%; }";
  ptr += ".corr-24 { height: 24%; }";
  ptr += ".corr-25 { height: 25%; }";
  ptr += ".corr-26 { height: 26%; }";
  ptr += ".corr-27 { height: 27%; }";
  ptr += ".corr-28 { height: 28%; }";
  ptr += ".corr-29 { height: 29%; }";
  ptr += ".corr-30 { height: 30%; }";
  ptr += ".corr-31 { height: 31%; }";
  ptr += ".corr-32 { height: 32%; }";
  ptr += ".corr-33 { height: 33%; }";
  ptr += ".corr-34 { height: 34%; }";
  ptr += ".corr-35 { height: 35%; }";
  ptr += ".corr-36 { height: 36%; }";
  ptr += ".corr-37 { height: 37%; }";
  ptr += ".corr-38 { height: 38%; }";
  ptr += ".corr-39 { height: 39%; }";
  ptr += ".corr-40 { height: 40%; }";
  ptr += ".corr-41 { height: 41%; }";
  ptr += ".corr-42 { height: 42%; }";
  ptr += ".corr-43 { height: 43%; }";
  ptr += ".corr-44 { height: 44%; }";
  ptr += ".corr-45 { height: 45%; }";
  ptr += ".corr-46 { height: 46%; }";
  ptr += ".corr-47 { height: 47%; }";
  ptr += ".corr-48 { height: 48%; }";
  ptr += ".corr-49 { height: 49%; }";
  ptr += ".corr-50 { height: 50%; }";
  ptr += ".corr-51 { height: 51%; }";
  ptr += ".corr-52 { height: 52%; }";
  ptr += ".corr-53 { height: 53%; }";
  ptr += ".corr-54 { height: 54%; }";
  ptr += ".corr-55 { height: 55%; }";
  ptr += ".corr-56 { height: 56%; }";
  ptr += ".corr-57 { height: 57%; }";
  ptr += ".corr-58 { height: 58%; }";
  ptr += ".corr-59 { height: 59%; }";
  ptr += "";
  ptr += ".corr-60 { height: 60%; }";
  ptr += ".corr-61 { height: 61%; }";
  ptr += ".corr-62 { height: 62%; }";
  ptr += ".corr-63 { height: 63%; }";
  ptr += ".corr-64 { height: 64%; }";
  ptr += ".corr-65 { height: 65%; }";
  ptr += ".corr-66 { height: 66%; }";
  ptr += ".corr-67 { height: 67%; }";
  ptr += ".corr-68 { height: 68%; }";
  ptr += ".corr-69 { height: 69%; }";
  ptr += ".corr-70 { height: 70%; }";
  ptr += ".corr-71 { height: 71%; }";
  ptr += ".corr-72 { height: 72%; }";
  ptr += ".corr-73 { height: 73%; }";
  ptr += ".corr-74 { height: 74%; }";
  ptr += ".corr-75 { height: 75%; }";
  ptr += ".corr-76 { height: 76%; }";
  ptr += ".corr-77 { height: 77%; }";
  ptr += ".corr-78 { height: 78%; }";
  ptr += ".corr-79 { height: 79%; }";
  ptr += ".corr-80 { height: 80%; }";
  ptr += ".corr-81 { height: 81%; }";
  ptr += ".corr-82 { height: 82%; }";
  ptr += ".corr-83 { height: 83%; }";
  ptr += ".corr-84 { height: 84%; }";
  ptr += ".corr-85 { height: 85%; }";
  ptr += ".corr-86 { height: 86%; }";
  ptr += ".corr-87 { height: 87%; }";
  ptr += ".corr-88 { height: 88%; }";
  ptr += ".corr-89 { height: 89%; }";
  ptr += ".corr-90 { height: 90%; }";
  ptr += ".corr-91 { height: 91%; }";
  ptr += ".corr-92 { height: 92%; }";
  ptr += ".corr-93 { height: 93%; }";
  ptr += ".corr-94 { height: 94%; }";
  ptr += ".corr-95 { height: 95%; }";
  ptr += ".corr-96 { height: 96%; }";
  ptr += ".corr-97 { height: 97%; }";
  ptr += ".corr-98 { height: 98%; }";
  ptr += ".corr-99 { height: 99%; }";
  ptr += ".corr-100 { height: 100%; border-radius: 20px; }";

  return ptr;
}
